#!/bin/bash -x
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

set -e

## Variable Definitions. ##

# Public directory for the repository.
PUBLIC_DIR=${OPENSHIFT_REPO_DIR}/public
# Current directory.
THIS_DIR=${OPENSHIFT_REPO_DIR}/.openshift/action_hooks
# Composer directory.
COMPOSER_DIR=${OPENSHIFT_PHP_DIR}/composer
# Drush directory.
DRUSH_DIR=${OPENSHIFT_PHP_DIR}/composer/.composer/vendor/drush
# Bash profile file.
PROFILE_FILE=${OPENSHIFT_DATA_DIR}/.bash_profile
# Composer bin directory path.
export COMPOSER_BIN=${OPENSHIFT_PHP_DIR}/composer/.composer/vendor/bin
# Current downloads directory.
CURRENT_DOWNLOAD=${OPENSHIFT_DATA_DIR}downloads/current

# Build PHP extra's
# Update conf/ini filesand install pecl extensions
${OPENSHIFT_PHP_DIR}/bin/control build

# Composer is already installed as per
# https://github.com/boekkooi/openshift-cartridge-php#composerpear
# So install Drush support to the application if not installed.
if [ ! -d "$DRUSH_DIR" ]; then
  # Install Drush.
  echo "Installing composer"
  composer global require drush/drush
  echo

  #Add Drush to base_profile only if it's not previously added.
  if ! grep -q '/.composer/vendor/bin' "${PROFILE_FILE}" ; then
    echo "Editing ${PROFILE_FILE} to load Drush"
    echo "PATH=${OPENSHIFT_PHP_DIR}/composer/.composer/vendor/bin:\$PATH" >> ${OPENSHIFT_DATA_DIR}/.bash_profile
    echo
    echo "source ${OPENSHIFT_DATA_DIR}/.bash_profile"
    echo
  fi
fi

# Download and install Drupal latest version if needed.
if [ ! -d "${CURRENT_DOWNLOAD}" ]; then
  mkdir -p ${OPENSHIFT_TMP_DIR}drupal
  echo "Download the latest version of Drupal 8"
  echo

  mkdir -p ${OPENSHIFT_DATA_DIR}downloads
  if ! ${COMPOSER_BIN}/drush dl drupal-8 --destination=${OPENSHIFT_DATA_DIR}downloads --yes
  then
    echo "ERROR: Unable download and install Drupal."
    exit 7
  fi
else
  echo "Do nothing"
fi
